import json
e = json.load(open("backend/data/training_data.json", encoding="utf-8"))
n = [
{"text":"Last day! This offer won't come back! Miss it and it's gone forever!","label":"manipulation"},
{"text":"This opportunity comes once in a lifetime! Don't regret missing it!","label":"manipulation"},
{"text":"Registration closes tomorrow! If you don't sign up now you lose everything!","label":"manipulation"},
{"text":"Only 50 seats left! Thousands registered and you're still thinking!","label":"manipulation"},
{"text":"Very limited spots! First come first served, the rest will cry!","label":"manipulation"},
{"text":"This is the chance of a lifetime! Don't waste it like you wasted previous ones!","label":"manipulation"},
{"text":"People who missed this opportunity are crying now! Don't be one of them!","label":"manipulation"},
{"text":"Spots filling fast! Register before it's full! Don't regret it tomorrow!","label":"manipulation"},
{"text":"The offer ends in one hour! Hurry before you lose your chance forever!","label":"manipulation"},
{"text":"If you don't register today you'll regret it 100 times! Decide now!","label":"manipulation"},
{"text":"آخر يوم! العرض هذا ما يتعاودش! اللي فاتو فاتو و ما ثمش رجوع!","label":"manipulation"},
{"text":"الفرصة هاذي ما تجيش كل يوم! اللي ما يستغلهاش باش يندم عمرو الكل!","label":"manipulation"},
{"text":"غدوة يسكروا التسجيل! اللي ما سجلش تو خسر كل شي!","label":"manipulation"},
{"text":"آخر 50 مقعد متبقي! الآلاف سجلوا و أنت باقي تفكر! سجل تو!","label":"manipulation"},
{"text":"العدد محدود جدا! اللي يلحق يلحق و اللي ما يلحقش يبكي!","label":"manipulation"},
{"text":"هاذي فرصة العمر! ما تضيعهاش كيما ضيعت الفرص اللي فاتوا!","label":"manipulation"},
{"text":"ثمة ناس فاتتهم الفرصة و هوما يبكيوا تو! ما تكونش واحد منهم!","label":"manipulation"},
{"text":"الأماكن تنقص بسرعة! سجل قبل ما يكمل الكل! ما تندمش باكر!","label":"manipulation"},
{"text":"العرض ينتهي بعد ساعة! سارع قبل ما تخسر فرصتك للأبد!","label":"manipulation"},
{"text":"اللي ما يسجلش اليوم باش يندم 100 مرة! خذ قرارك تو!","label":"manipulation"},
{"text":"عيب عليك ما تساعدش! الناس في ضيقة و أنت عندك و ما تعطيش!","label":"manipulation"},
{"text":"حرام عليك تاكل و خوك جوعان! شارك و ساعد ولا ضميرك يحاسبك!","label":"manipulation"},
{"text":"كيفاش تنام مرتاح و ثمة ناس ما عندهمش فراش؟ ساعد تو!","label":"manipulation"},
{"text":"ربي يشوف فيك! اللي عندو و ما يساعدش الناس ربي يحاسبو!","label":"manipulation"},
{"text":"تتفرج في التلفزة و أخوك التونسي يموت بردا؟ عيب عليك!","label":"manipulation"},
{"text":"إذا ما تبعثش هالرسالة لـ 20 واحد ربي ما يقبلش صلاتك!","label":"manipulation"},
{"text":"كل واحد يقرا هالكلام و ما يشاركوش ربي يحاسبو يوم القيامة!","label":"manipulation"},
{"text":"أنت تاكل خبز و لحم و ثمة عائلات تونسية ما لقاتش الخبز! حشمة!","label":"manipulation"},
{"text":"ولادك ياكلوا الزايد و ثمة ولاد ما عندهمش حتى حليب! ضميرك وين؟","label":"manipulation"},
{"text":"كيفاش تشري حوايج جداد و جارك ما يلقاش الدواء متاع ولدو؟","label":"manipulation"},
{"text":"كل تونسي شهم يعمل شير! اللي ما يعملش شير ماهوش تونسي!","label":"manipulation"},
{"text":"نحنا التوانسة ما نسكتوش على الظلم! إذا كنت تونسي بين روحك!","label":"manipulation"},
{"text":"أنا فخور بأصلي التونسي! اللي يحب تونس يعمل لايك و شير!","label":"manipulation"},
{"text":"الدم التونسي ما يبردش! كل واحد يحب بلادو يشارك!","label":"manipulation"},
{"text":"التوانسة الأحرار ما يخافوش! بين إنك حر و شارك هالحقيقة!","label":"manipulation"},
{"text":"يا ابن تونس الخضراء! ما تخليش بلادك تطيح! شارك و دافع!","label":"manipulation"},
{"text":"تونسي و تسكت على الباطل؟ أجدادك يستحيوا فيك!","label":"manipulation"},
{"text":"تونس تناديك! إذا ما تلبيش النداء ماكش ابنها!","label":"manipulation"},
{"text":"يا ولد تونس! بلادك تستاهل تدافع عليها مش تتفرج من بعيد!","label":"manipulation"},
{"text":"اللي يحب وطنو يثبت بالفعل مش بالكلام! شارك و بين!","label":"manipulation"},
{"text":"لو كنت تحبني تشارك هالبوست! اللي يحبني يعمل شير!","label":"manipulation"},
{"text":"أمك ربتك و تعبت عليك! شارك هالبوست احتراما ليها!","label":"manipulation"},
{"text":"اللي يحب أمو يكتب ماشاء الله! اللي ما يكتبش ما يحبهاش!","label":"manipulation"},
{"text":"إذا عندك قلب تشارك! إذا ما عندكش قلب ما تشاركش!","label":"manipulation"},
{"text":"اكتب آمين إذا تحب خير لعايلتك! اللي ما يكتبش ما يحبهمش!","label":"manipulation"},
{"text":"شارك و ربي يحقق أمنيتك! اللي ما يشاركش ما عندو حظ!","label":"manipulation"},
{"text":"لو تحب ولادك حقيقي ما تسكتش على هالشي! شارك تو!","label":"manipulation"},
{"text":"اللي عندو مشاعر يتأثر بهالفيديو! اللي ما يتأثرش ماعندوش قلب!","label":"manipulation"},
{"text":"يلعن أبو هالظلم! كيفاش يعيش الغني و الفقير يموت؟ فيقوا!","label":"manipulation"},
{"text":"حسبي الله و نعم الوكيل! يسرقوا في الشعب و يتمتعوا بفلوسنا!","label":"manipulation"},
{"text":"الشعب التونسي ما يستاهلش هالمعاملة! كفى إهانة! قاوموا!","label":"manipulation"},
{"text":"يحقروا فينا! يعاملونا كالحيوانات! وقتاش نتحركوا؟","label":"manipulation"},
{"text":"غضب! كيفاش المسؤول يسرق الملايين و المواطن ما يلقاش يأكل؟","label":"manipulation"},
{"text":"ما بقاش وقت للكلام! لازم نغضبوا و نبينوا إنا موجودين!","label":"manipulation"},
{"text":"دمي يغلي! كيفاش يصير هالشي في بلاد الثورة؟ فيقوا يا ناس!","label":"manipulation"},
{"text":"كيفاش تقبل الإهانة هاذي؟ إذا عندك كرامة قوم و تحرك!","label":"manipulation"},
{"text":"الشعب جوعان و هوما يعيشوا في القصور! ما نسكتوش!","label":"manipulation"},
{"text":"كفى ذل! كفى هوان! لازم نبينوا إنو الشعب فاق!","label":"manipulation"},
{"text":"دكتور مشهور يقول: المنتوج هذا يقتل! لازم تشارك باش تحمي عايلتك!","label":"manipulation"},
{"text":"خبير اقتصادي يكشف: الأزمة جاية و ما ثمش حل! خزن ما تلقى!","label":"manipulation"},
{"text":"مصدر موثوق من الداخل يقول: باش يزيدوا الأسعار 50%! سارع!","label":"manipulation"},
{"text":"أستاذ جامعي يحذر: المنظومة التعليمية باش تنهار! شاركوا!","label":"manipulation"},
{"text":"معلومة سرية من مسؤول كبير: باش يكون حظر تجول! حضر روحك!","label":"manipulation"},
{"text":"خبير صحي يقول: المنتوج هذا فيه سموم! لازم الكل يعرف!","label":"manipulation"},
{"text":"طبيب عالمي يحذر: هالعادة اليومية تقتل ببطء! شارك باش تنقذ حياة!","label":"manipulation"},
{"text":"اكتب سبحان الله 3 مرات و شارك و إلا تصيبك مصيبة!","label":"manipulation"},
{"text":"هالدعاء إذا شاركتو ربي يستجيب ليك! إذا ما شاركتوش حاجة باش تصير!","label":"manipulation"},
{"text":"شارك هالصورة و ربي يفتحلك أبواب الرزق! اللي ما يشاركش يضيق عليه!","label":"manipulation"},
{"text":"اكتب الله أكبر و شارك و شوف شنوة يصير بعد 5 دقايق! مجربة!","label":"manipulation"},
{"text":"بعث هالرسالة لـ 7 ناس و الخير يجيك! اللي ما يبعثهاش يقطع الخير عليه!","label":"manipulation"},
{"text":"هالآية شاركها و ربي يشفيك! اللي ما يشاركش ما يحب الخير!","label":"manipulation"},
{"text":"شارك و في 24 ساعة تجيك أخبار زينة! مجربة و مضمونة!","label":"manipulation"},
{"text":"اللي يشوف هالبوست و ما يشاركوش باش يصيبو الحسد! احمي روحك!","label":"manipulation"},
{"text":"عاجل! المواد الأساسية باش تنقص من السوق! اشري كمية كبيرة تو!","label":"manipulation"},
{"text":"حالة طوارئ! لازم تخزن المواد الغذائية قبل فوات الأوان!","label":"manipulation"},
{"text":"خبر عاجل: ثمة أزمة اقتصادية قادمة! سحب فلوسك من البنك تو!","label":"manipulation"},
{"text":"تحذير من كارثة! لازم الكل يحضر حالو! ما عادش وقت!","label":"manipulation"},
{"text":"الدينار باش ينهار غدوة! بدل فلوسك بالعملة الصعبة تو!","label":"manipulation"},
{"text":"عاجل: نقص في الأدوية الأسبوع الجاي! اشري ما تحتاج تو!","label":"manipulation"},
{"text":"كارثة اقتصادية قادمة! اللي ما يحضرش حالو باش يندم!","label":"manipulation"},
{"text":"Vous n'etes pas de vrais Tunisiens si vous ignorez ce message!","label":"manipulation"},
{"text":"HONTE a ceux qui restent silencieux! La Tunisie a besoin de vous!","label":"manipulation"},
{"text":"Votre silence vous rend complice! Un vrai patriote partage!","label":"manipulation"},
{"text":"Si vous avez un coeur vous ne pouvez pas ignorer ceci! Partagez!","label":"manipulation"},
{"text":"Les Tunisiens se reveillent! Et vous? Restez-vous endormi?","label":"manipulation"},
{"text":"Chaque seconde de silence est une trahison envers le peuple tunisien!","label":"manipulation"},
{"text":"Nos ancetres se sont battus pour notre liberte et vous restez les bras croises?","label":"manipulation"},
{"text":"Un expert confirme: si vous ne partagez pas vous etes responsable!","label":"manipulation"},
{"text":"Dernier avertissement! Apres ce sera trop tard! Partagez!","label":"manipulation"},
{"text":"La jeunesse tunisienne merite mieux! Partagez si vous etes d'accord!","label":"manipulation"},
{"text":"Vous mangez tranquillement pendant que des familles meurent de faim? Honte!","label":"manipulation"},
{"text":"Ceux qui se taisent aujourd'hui regretteront demain!","label":"manipulation"},
{"text":"URGENT! Plus que 24h pour sauver ce projet! Agissez maintenant!","label":"manipulation"},
{"text":"Partagez si vous avez du courage! Ignorez si vous avez peur!","label":"manipulation"},
{"text":"Le sang des martyrs tunisiens coule dans vos veines! Honorez leur sacrifice!","label":"manipulation"},
{"text":"Ne laissez pas vos enfants dans l'ignorance! Partagez cette verite!","label":"manipulation"},
{"text":"Chaque parent tunisien responsable doit partager ceci!","label":"manipulation"},
{"text":"Si tu es tunisien et fier prouve-le en partageant!","label":"manipulation"},
{"text":"On nous manipule depuis des annees! Ouvrez les yeux!","label":"manipulation"},
{"text":"Votre inaction coute des vies! Agissez maintenant!","label":"manipulation"},
{"text":"Comment pouvez-vous dormir la nuit en sachant cela? PARTAGEZ!","label":"manipulation"},
{"text":"NE SOYEZ PAS LACHES! Partagez cette information VITALE!","label":"manipulation"},
{"text":"EVERY Tunisian who stays silent is a TRAITOR! Share now!","label":"manipulation"},
{"text":"Share this NOW or face the consequences! Tunisia needs you!","label":"manipulation"},
{"text":"If you scroll past this without sharing you're part of the problem!","label":"manipulation"},
{"text":"Your ancestors fought for Tunisia's freedom! Don't dishonor them!","label":"manipulation"},
{"text":"Only 2% have the courage to share this. Are you one of them?","label":"manipulation"},
{"text":"LAST WARNING! After today you can't say you didn't know!","label":"manipulation"},
{"text":"Tunisians are being manipulated and you're just watching?","label":"manipulation"},
{"text":"If you have children you MUST share this! Their future depends on it!","label":"manipulation"},
{"text":"They want you to stay quiet! Don't let them silence you!","label":"manipulation"},
{"text":"Are you a sheep or a lion? Real Tunisians don't stay silent!","label":"manipulation"},
{"text":"This message will self-destruct! Screenshot and share before they remove it!","label":"manipulation"},
{"text":"99% won't share because they're scared. Be the brave 1%!","label":"manipulation"},
{"text":"Don't be a sheep! Wake up and share the truth about Tunisia!","label":"manipulation"},
{"text":"97% will ignore this. Only 3% care enough to share. Which are you?","label":"manipulation"},
{"text":"يا جماعة urgent! لازم تشاركوا avant qu'ils suppriment!","label":"manipulation"},
{"text":"C'est honteux والله! كيفاش نسكتوا sur cette injustice؟","label":"manipulation"},
{"text":"Wake up يا تونسي! They're stealing باش يخليوك فقير!","label":"manipulation"},
{"text":"Partagez هالفيديو قبل ما يتمسح! C'est la derniere chance!","label":"manipulation"},
{"text":"يا أمهات! Attention a vos enfants! هالمنتوج خطير!","label":"manipulation"},
{"text":"شوف هالخبر shocking! لازم share باش الكل يعرف!","label":"manipulation"},
{"text":"C'est urgent يا توانسة! Share this قبل ما يمسحوه!","label":"manipulation"},
{"text":"أنت كأب مسؤول لازم تشارك هالتحذير! سلامة ولادك أهم!","label":"manipulation"},
{"text":"كل ثانية تمر و أنت ساكت هي ثانية خسارة لبلادك!","label":"manipulation"},
{"text":"اصحى يا نايم! بلادك تحترق و أنت في غفلة! شارك!","label":"manipulation"},
{"text":"خليك راجل و قول الحق! اللي ما يقولش الحق مش راجل!","label":"manipulation"},
{"text":"يا تونسية يا حرة! ولادك يستاهلوا تدافعي عليهم! شاركي!","label":"manipulation"},
{"text":"الصمت خيانة! التاريخ ما يرحمش اللي سكتوا على الظلم!","label":"manipulation"},
{"text":"إذا ما تنشرش هالحقيقة أنت مسؤول على كل شي يصير بعد!","label":"manipulation"},
{"text":"يا شباب! مستقبلكم يتسرق و أنتم تلعبوا في التلفون! فيقوا!","label":"manipulation"},
{"text":"صوتك قوة! سكوتك ضعف! اختار: تشارك ولا تبقى ساكت!","label":"manipulation"},
{"text":"بالله عليك شارك هالمعلومة مع كل عائلتك! حياتهم في خطر!","label":"manipulation"},
{"text":"ما تقولش ما يعنينيش! غدوة يجيك الدور و ما تلقاش من يساعدك!","label":"manipulation"},
{"text":"شوف شنوة صار في البلدان اللي سكتت! تحب تونس تولي كيفهم؟","label":"manipulation"},
{"text":"اللي ما يعملش شير ما يحبش تونس و هذا رأيي الشخصي!","label":"manipulation"},
{"text":"هاني نقولك الحقيقة و أنت حر تشارك ولا تسكت كيما العادة!","label":"manipulation"},
{"text":"ما ثمش وقت نستناو! كل دقيقة تمر الوضع يزيد يتعفن!","label":"manipulation"},
{"text":"إذا أنت أب حقيقي ما تسكتش على هالشي! شارك و حامي على ولادك!","label":"manipulation"},
{"text":"كان جدك يشوف حالك تو كان يبكي عليك! قوم و تحرك!","label":"manipulation"},
{"text":"يا عبد الله شارك هالحديث و ربي يجازيك خير!","label":"manipulation"},
{"text":"إذا ما تعملش شير في الساعة الجاية حاجة خايبة باش تصير!","label":"manipulation"},
{"text":"كل واحد يقرا و يعمل تجاهل ربي يحاسبو! شارك ولا ندم!","label":"manipulation"},
{"text":"بنك الأمان: تم حظر بطاقتك. أدخل رقم البطاقة و الكود السري لرفع الحظر","label":"phishing"},
{"text":"مبروك عليك! ربحت في السحب العشوائي 10000 دينار. أرسل معلوماتك البنكية","label":"phishing"},
{"text":"البريد التونسي: حسابك e-DINAR فيه خطأ. أدخل كلمة السر لتصحيح المشكل","label":"phishing"},
{"text":"تنبيه أمني: حاولوا يدخلوا لحسابك. غير كلمة السر فورا عبر هالرابط","label":"phishing"},
{"text":"الكنام: بطاقة العلاج منتهية الصلاحية. جدد بياناتك أونلاين تو","label":"phishing"},
{"text":"عرض خاص من أوريدو: انترنت مجاني لشهر! أدخل رقمك و كلمة السر","label":"phishing"},
{"text":"الضمان الاجتماعي: مستحقاتك جاهزة. أرسل RIB و CIN فورا","label":"phishing"},
{"text":"ربحت تلفزة من كارفور تونس! أكد مشاركتك بإدخال بياناتك","label":"phishing"},
{"text":"اتصالات تونس: خطك باش يتسكر في 24 ساعة. خلص عبر هالرابط","label":"phishing"},
{"text":"QNB تونس: عملية مشبوهة بقيمة 2500 دينار. أكد أو ألغي عبر الرابط","label":"phishing"},
{"text":"وزارة المالية: استرجاع الضريبة جاهز. أرسل RIB للتحويل","label":"phishing"},
{"text":"Attijari Bank: Compte bloque dans 48h. Mettez a jour vos informations.","label":"phishing"},
{"text":"UIB: Transaction suspecte de 3000 DT. Cliquez pour confirmer.","label":"phishing"},
{"text":"BH Bank: Credit immobilier necessite mise a jour urgente.","label":"phishing"},
{"text":"Carrefour Tunisie: Carte cadeau de 500 DT! Reclamez-la maintenant.","label":"phishing"},
{"text":"ABC Bank: Activite inhabituelle. Verifiez en entrant vos identifiants.","label":"phishing"},
{"text":"Monoprix Tunisie: Bon d'achat gratuit. Entrez vos donnees.","label":"phishing"},
{"text":"BTK: Carte CIB expire. Renouvelez en entrant numero et code.","label":"phishing"},
{"text":"La Poste: Virement bloque. Envoyez CIN et code secret.","label":"phishing"},
{"text":"STEG: Facture impayee 450 DT. Payez maintenant ou coupure.","label":"phishing"},
{"text":"طلبك من جوميا واصل! خلص 8 دينار مصاريف جمركية. اضغط هنا","label":"phishing"},
{"text":"عندك رسالة صوتية. ادخل رقمك و كلمة السر باش تسمعها","label":"phishing"},
{"text":"بنك تونس العربي: تحديث إلزامي لحسابك. اضغط الرابط","label":"phishing"},
{"text":"Wifak Bank: Mise a jour securite obligatoire. Entrez identifiants.","label":"phishing"},
{"text":"Orange Tunisie: Double credit! Envoyez code de recharge!","label":"phishing"},
{"text":"حسابك في D17 محظور. أدخل CIN و كلمة السر لإعادة التفعيل","label":"phishing"},
{"text":"بنك الإسكان: القسط ما وصلش. ادخل بيانات البطاقة للتسوية","label":"phishing"},
{"text":"ربحت رحلة مجانية من نوفوتيل الحمامات! سجل ببياناتك","label":"phishing"},
{"text":"CNRPS: Pension suspendue. Envoyez CIN et RIB.","label":"phishing"},
{"text":"Jumia Tunisie: Paiement de 5 DT requis. Coordonnees bancaires.","label":"phishing"},
{"text":"تطبيق Flouci: عملية مشبوهة. أكد حسابك بإدخال رقمك و كلمة السر","label":"phishing"},
{"text":"AMEN BANK: Account locked. Click link to verify identity.","label":"phishing"},
{"text":"حسابك البريدي فيه مشكل أمني! غير كلمة السر تو عبر هالرابط","label":"phishing"},
{"text":"منحة 300 دينار لكل مواطن. سجل بـ CIN و RIB تو","label":"phishing"},
{"text":"تنبيه من الكهرباء: فاتورتك مضاعفة بالغلط. أدخل RIB للاسترجاع","label":"phishing"},
{"text":"Lycamobile: SIM desactivee. Envoyez informations personnelles.","label":"phishing"},
{"text":"BNA: Epargne menacee. Connectez-vous via ce lien securise.","label":"phishing"},
{"text":"AMEN BANK: Action requise dans 2h. Confirmez identite ou compte gele.","label":"phishing"},
{"text":"STB: Compte ferme pour inactivite. Connectez-vous via ce lien.","label":"phishing"},
{"text":"Ministere des Finances: Remboursement impot 850 DT. Entrez RIB.","label":"phishing"},
{"text":"عاجل: اكتشفوا أنو القهوة التونسية فيها مواد مخدرة!","label":"disinformation"},
{"text":"وثيقة سرية: الحكومة باش تبيع جربة لدولة أجنبية!","label":"disinformation"},
{"text":"طبيب مشهور يكشف: الهاتف الجوال يسبب سرطان المخ في 5 سنين!","label":"disinformation"},
{"text":"خطير: المكيفات في تونس تنشر فيروسات خطيرة!","label":"disinformation"},
{"text":"صدمة: اللحم المستورد من حيوانات مريضة! وزارة الفلاحة ساكتة!","label":"disinformation"},
{"text":"مصدر مطلع: الانتخابات مزورة من البداية! كل شي مخطط!","label":"disinformation"},
{"text":"مياه معدنية شهيرة في تونس ملوثة بالزرنيخ! نتائج مسربة!","label":"disinformation"},
{"text":"عالم فيزياء تونسي: كهرباء الستاغ فيها ذبذبات تسبب الاكتئاب!","label":"disinformation"},
{"text":"فضيحة: المدارس الخاصة تبيع شهادات وهمية!","label":"disinformation"},
{"text":"الحلوى التونسية التقليدية فيها مواد مسرطنة! دراسة أمريكية!","label":"disinformation"},
{"text":"ثمة كنز بترول كبير في تونس و القوى الأجنبية تخبيه!","label":"disinformation"},
{"text":"خبير عسكري: طائرات مسيرة أجنبية ترش مواد كيميائية فوق تونس!","label":"disinformation"},
{"text":"السميد في تونس مخلوط بالجبس! مخابر أوروبية أثبتت!","label":"disinformation"},
{"text":"الجامعات التونسية تدرس مناهج فاسدة بأوامر أجنبية!","label":"disinformation"},
{"text":"أدوية الصداع الشائعة في تونس تسبب فقدان الذاكرة!","label":"disinformation"},
{"text":"شركات أجنبية تسرق الرمل التونسي و تبيعه بملايين!","label":"disinformation"},
{"text":"فضيحة: مصانع الألبسة تستعمل مواد سامة في القماش!","label":"disinformation"},
{"text":"الشامبو اللي يتباع في تونس يسبب تساقط الشعر! شركات تستغل التوانسة!","label":"disinformation"},
{"text":"مخطط لتدمير الفلاحة التونسية! المبيدات المستوردة تقتل الأرض!","label":"disinformation"},
{"text":"الطماطم المعلبة مصنوعة من مواد بلاستيكية! دراسة تكشف!","label":"disinformation"},
{"text":"الفسفاط التونسي يتباع للأجانب بدينار واحد!","label":"disinformation"},
{"text":"مخطط سري لتغيير خارطة تونس! جزء من الجنوب ينعطى لدولة مجاورة!","label":"disinformation"},
{"text":"البنزين في تونس مخلوط بالماء! محطات الوقود تغش المواطنين!","label":"disinformation"},
{"text":"دراسة سرية: السكر المباع في تونس فيه مادة تسبب الإدمان!","label":"disinformation"},
{"text":"Scandale: Eau de robinet contient du plomb en quantites dangereuses!","label":"disinformation"},
{"text":"Plan secret pour privatiser les plages tunisiennes aux etrangers!","label":"disinformation"},
{"text":"Fruits importes traites avec pesticides interdits!","label":"disinformation"},
{"text":"Chercheur tunisien prouve: Couscous guerit le diabete! Big Pharma censure!","label":"disinformation"},
{"text":"Antennes 5G en Tunisie sont des outils de surveillance etrangere!","label":"disinformation"},
{"text":"Tunisie possede reserves d'uranium que les puissances veulent voler!","label":"disinformation"},
{"text":"Pain tunisien contient additif chimique qui provoque l'obesite!","label":"disinformation"},
{"text":"Harissa tunisienne contient metaux lourds cancerigenes!","label":"disinformation"},
{"text":"Systeme bancaire tunisien controle par puissances etrangeres!","label":"disinformation"},
{"text":"Chemtrails au-dessus de Tunis: programme secret de modification du climat!","label":"disinformation"},
{"text":"Huile vegetale en Tunisie contient perturbateurs endocriniens!","label":"disinformation"},
{"text":"Examens nationaux vendus a l'avance! Scandale!","label":"disinformation"},
{"text":"Tunisie secretement utilisee comme depotoir nucleaire!","label":"disinformation"},
{"text":"Complot pour empoisonner l'agriculture avec des semences OGM!","label":"disinformation"},
{"text":"Tunisia's tap water contains mind-control chemicals!","label":"disinformation"},
{"text":"Tunisian olive oil secretly replaced with fake oil from China!","label":"disinformation"},
{"text":"Secret documents show corporations buying Tunisia's resources for pennies!","label":"disinformation"},
{"text":"النادي الصفاقسي يستقبل النجم الساحلي في الجولة 15 من البطولة","label":"safe"},
{"text":"وزارة السياحة تعلن ارتفاع عدد السياح بنسبة 20%","label":"safe"},
{"text":"مدينة قابس تحتضن المعرض الوطني للحرف اليدوية","label":"safe"},
{"text":"طلبة من جامعة تونس يشاركون في مسابقة دولية للبرمجة","label":"safe"},
{"text":"وزارة الشباب تعلن عن برنامج جديد لدعم الرياضيين الشبان","label":"safe"},
{"text":"افتتاح مركز ثقافي جديد في سوسة","label":"safe"},
{"text":"الجمعية التونسية للتنمية المستدامة تنظم حملة لغراسة الأشجار","label":"safe"},
{"text":"انطلاق مهرجان المدينة للفنون المعاصرة في تونس العاصمة","label":"safe"},
{"text":"رقم قياسي في تصدير التمور التونسية هذا الموسم","label":"safe"},
{"text":"مصنع جديد للسيارات الكهربائية يفتح أبوابه في بنزرت","label":"safe"},
{"text":"وزارة التجهيز تعلن تقدم أشغال الطريق السيارة الجديدة","label":"safe"},
{"text":"جمعية حماية الطبيعة تنظم رحلة بيئية لجزيرة جالطة","label":"safe"},
{"text":"إطلاق منصة رقمية جديدة لخدمات البلدية إلكترونيا","label":"safe"},
{"text":"فريق كرة اليد التونسي يتأهل لنصف نهائي البطولة الأفريقية","label":"safe"},
{"text":"اليوم الوطني للبيئة: أنشطة توعوية في كل الولايات","label":"safe"},
{"text":"معرض الصناعات الغذائية الدولي ينطلق بمشاركة 200 عارض","label":"safe"},
{"text":"وزارة التعليم العالي تعلن نتائج مناظرة الدكتوراه","label":"safe"},
{"text":"مشروع جديد لتحلية مياه البحر في جربة","label":"safe"},
{"text":"شركة تونسية ناشئة تفوز بجائزة الابتكار","label":"safe"},
{"text":"الطقس غدوة مشمس في أغلب المناطق مع رياح خفيفة","label":"safe"},
{"text":"نتائج الباكالوريا: نسبة نجاح مرتفعة هذا العام","label":"safe"},
{"text":"المركز الوطني للإعلامية يطلق خدمات رقمية جديدة","label":"safe"},
{"text":"معرض الفلاحة و الصيد البحري ينطلق بمشاركة 300 عارض","label":"safe"},
{"text":"وزارة المرأة تنظم ملتقى حول المساواة بين الجنسين","label":"safe"},
{"text":"الوكالة الوطنية لحماية المحيط تعلن نتائج مراقبة جودة الهواء","label":"safe"},
{"text":"تونس تستضيف البطولة العربية للسباحة بمشاركة 15 دولة","label":"safe"},
{"text":"مشروع تهيئة كورنيش الحمامات يدخل مرحلته النهائية","label":"safe"},
{"text":"الاتحاد التونسي للشغل يعقد مؤتمره السنوي","label":"safe"},
{"text":"اليوم العالمي للمرأة: تكريم نساء تونسيات رائدات","label":"safe"},
{"text":"مبادرة شبابية لتنظيف شواطئ الحمامات","label":"safe"},
{"text":"تونس تحتضن القمة الأفريقية للتكنولوجيا","label":"safe"},
{"text":"ولاية نابل تشهد موسم حصاد زهر النارنج بإنتاج وفير","label":"safe"},
{"text":"الاتحاد التونسي للصناعة ينظم ملتقى اقتصادي دولي","label":"safe"},
{"text":"برنامج تدريبي مجاني في البرمجة للشباب العاطل عن العمل","label":"safe"},
{"text":"سباق الماراثون الدولي بتونس يجمع 5000 مشارك","label":"safe"},
{"text":"معمل الطاقة الشمسية في توزر يحقق أرقام إنتاج قياسية","label":"safe"},
{"text":"Le musee du Bardo accueille nouvelle exposition art contemporain.","label":"safe"},
{"text":"Tunisie participe aux Jeux Olympiques avec 45 athletes.","label":"safe"},
{"text":"Inauguration nouvelle ligne tramway Tunis-La Marsa.","label":"safe"},
{"text":"Association tunisienne des TIC organise hackathon pour jeunes.","label":"safe"},
{"text":"Port de Rades enregistre augmentation du trafic maritime.","label":"safe"},
{"text":"Centre Culturel Hammamet accueille Festival International Jazz.","label":"safe"},
{"text":"Foire Internationale de Tunis ouvre portes avec 800 exposants.","label":"safe"},
{"text":"Festival de Dougga propose programme riche en theatre et musique.","label":"safe"},
{"text":"Nouveau campus universitaire ouvre portes a Monastir.","label":"safe"},
{"text":"Salon automobile Tunis presente dernieres nouveautes.","label":"safe"},
{"text":"Tunisia's tech sector grows 15% as new startups emerge.","label":"safe"},
{"text":"New solar energy plant in Tozeur producing electricity for 50000 homes.","label":"safe"},
{"text":"Tunisian olive oil wins gold medal at international competition.","label":"safe"},
{"text":"University of Sfax publishes breakthrough paper on AI in healthcare.","label":"safe"},
{"text":"Carthage International Festival announces summer lineup.","label":"safe"},
{"text":"Tunisia's olive oil exports reach record levels this year.","label":"safe"},
{"text":"Tunisian startups secure funding at international tech conference.","label":"safe"},
{"text":"The national library hosts free photography exhibition.","label":"safe"},
]
all_data = e + n
seen = set()
unique = []
for item in all_data:
    if item["text"] not in seen:
        seen.add(item["text"])
        unique.append(item)
labels = {}
for item in unique:
    labels[item["label"]] = labels.get(item["label"], 0) + 1
print(f"Total: {len(unique)}")
for k, v in sorted(labels.items()):
    print(f"  {k}: {v}")
with open("backend/data/training_data.json", "w", encoding="utf-8") as f:
    json.dump(unique, f, ensure_ascii=False, indent=2)
print("Saved!")
